// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFu1keetzwNJGCqiQMqhmAChlX2NUblFw',
    appId: '1:916298539468:web:22f66ea75fc0283604fd69',
    messagingSenderId: '916298539468',
    projectId: 'fir-app-414da',
    authDomain: 'fir-app-414da.firebaseapp.com',
    storageBucket: 'fir-app-414da.appspot.com',
    measurementId: 'G-V6RYSM6SVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3CnpMIt2uwGs3nc8Se32wZOJkvLMrzlI',
    appId: '1:916298539468:android:a564a3dc5c032f3d04fd69',
    messagingSenderId: '916298539468',
    projectId: 'fir-app-414da',
    storageBucket: 'fir-app-414da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRSEvP7oiVdOytgV11lCqP8BjyGPKzcy0',
    appId: '1:916298539468:ios:5b1c74b3dd9efcd904fd69',
    messagingSenderId: '916298539468',
    projectId: 'fir-app-414da',
    storageBucket: 'fir-app-414da.appspot.com',
    iosClientId: '916298539468-4g5hbq47u0khlubrish8pvjo226r9pk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
